### ISSUE TITLE
Register your interest button has incorrect styling and data attribute

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/forms-product-page#11]
The button for `Register your interest` is receiving an underline when active. GOV.UK buttons aren't meant to do this.

I think this is because of the inverted styles getting applied and adding an underline.

GOV.UK Forms site:
<img width="528" alt="Screenshot 2022-06-09 at 13 36 35" src="https://user-images.githubusercontent.com/2204224/172848568-419f7956-b809-44a7-893c-489fc98f6495.png">
<img width="514" alt="Screenshot 2022-06-09 at 13 34 30" src="https://user-images.githubusercontent.com/2204224/172848574-785fde04-139b-4a0b-9600-e868036a5d8f.png">

Compare to Design System site:
<img width="422" alt="Screenshot 2022-06-09 at 13 37 50" src="https://user-images.githubusercontent.com/2204224/172848676-0dea5057-8d1e-47b3-a539-54c5ab9a3139.png">

## Data module

The button also seems to be missing `data-module="govuk-button"` which I think is needed to correctly shim the anchor for AT.

**Comment by aliuk2012** [comment]
Hi @edwardhorsford 

Thank you for raising this issue and sorry for the slow response, this should now be fixed in production.
